### ISSUE TITLE
Won't detect Shelter (Android work profile) apps

### ISSUE THREAD

**Issue by Barraguesh** [sduduzog/slim-launcher#54]
Loving the launcher but I use Shelter app for privacy purposes and it can't detect apps that are placed in a workspace, would be cool to add it because I use Whatsapp this way.

Shelter info: https://f-droid.org/en/packages/net.typeblog.shelter/

**Comment by sduduzog** [comment]
I also have work profile enabled on my phone and this is a real pain in a butt. I have been looking around and it seems this will be more complicated than I thought. Mostly because I am trying to run away from features that require permissions etc. just to give confidence to end-users about privacy concerns anyone might have.
